
{
  description = "Node app with fully vendored dependencies using node2nix and default.nix";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.05";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils, ... }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };

        # Import the default.nix generated by node2nix
        nodePackages = import ./default.nix {
          inherit pkgs system;
          nodejs = pkgs.nodejs_20;
        };
      in {
        packages.default = pkgs.stdenv.mkDerivation {
          pname = "hsp2json"; # or your package name
          version = "1.0.0";
          src = ./.;
          buildInputs = [ nodePackages.package  nodePackages.nodeDependencies ];
          installPhase = ''
            mkdir -p $out/bin
            cat > $out/bin/hsp2json <<EOF
            #!/bin/sh
            export NODE_PATH=${nodePackages.nodeDependencies}/lib/node_modules:${pkgs.typescript}/lib/node_modules
            export PATH=${nodePackages.nodeDependencies}/bin:${pkgs.typescript}/bin:$PATH
            exec ${pkgs.nodejs}/bin/node ${nodePackages.package}/lib/node_modules/hsp2json/convert.js "\$@"
            EOF
            chmod +x $out/bin/hsp2json
          '';
        };

        apps.default = flake-utils.lib.mkApp {
          drv = self.packages.${system}.default;
          exePath = "/bin/hsp2json";
        };
      });
}
