# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "install-0.13.0" = {
      name = "install";
      packageName = "install";
      version = "0.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/install/-/install-0.13.0.tgz";
        sha512 = "zDml/jzr2PKU9I8J/xyZBQn8rPCAY//UOYNmR01XwNwyfhEWObo2SWfSl1+0tm1u6PhxLwDnfsT/6jB7OUxqFA==";
      };
    };
    "npm-10.9.3" = {
      name = "npm";
      packageName = "npm";
      version = "10.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm/-/npm-10.9.3.tgz";
        sha512 = "6Eh1u5Q+kIVXeA8e7l2c/HpnFFcwrkt37xDMujD5be1gloWa9p6j3Fsv3mByXXmqJHy+2cElRMML8opNT7xIJQ==";
      };
    };
    "smart-buffer-4.2.0" = {
      name = "smart-buffer";
      packageName = "smart-buffer";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/smart-buffer/-/smart-buffer-4.2.0.tgz";
        sha512 = "94hK0Hh8rPqQl2xXc3HsaBoOXKV20MToPkcXvwbISWLEs+64sBq5kFgn2kJDHb1Pry9yrP0dxrCI9RRci7RXKg==";
      };
    };
  };
  args = {
    name = "hsp2json";
    packageName = "hsp2json";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."install-0.13.0"
      sources."npm-10.9.3"
      sources."smart-buffer-4.2.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "converter for HereSphere hsp file format";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
